name: Award Badge
on:
  pull_request_target:
    types: [closed]

jobs:
  badge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Parse delivery file
        id: delivery
        uses: ./.github/workflows/composite/get_delivery

      - name: Get application file
        run: wget "https://raw.githubusercontent.com/w3f/Grants-Program/master/applications/${{ steps.delivery.outputs.application-filename }}"

      - name: Parse application file
        id: parse-grant
        if: steps.files.outputs.filenames
        uses: alxs/parse-grant-application-action@v1
        with:
          path: "${{ steps.delivery.outputs.application-filename }}"

      - name: Leave badge comment if applicable
        if: steps.files.outputs.filenames && steps.delivery.outputs.milestone-number == 1 && steps.parse-grant.outputs.level != 1
        uses: thollander/actions-comment-pull-request@1.0.1
        with:
          message: >
            Congratulations on completing the first milestone of this grant!
            As part of the Grants Program, we want to help grant recipients acknowledge their grants publicly.
            To that end, we’ve created a [badge for projects](https://github.com/w3f/Grants-Program/blob/master/docs/grant-badge-guidelines.md)
            that successfully delivered their first milestone.<br/><br/>
            Please note that the badge must always be used strictly within the context of the delivered work, so please do not display it on
            your team or project's homepage unless accompanied by a short description of the grant.<br/><br/>
            Furthermore, you may now announce the grant publicly, though please remember to still observe the
            [foundation’s guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md) in doing so.
            In case you haven't done so yet, you may also reach out to grantspr@web3.foundation for feedback on your announcement and for cross-promotion.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
