name: Google Sheet Update
on:
  pull_request_target:
    types: [opened]

jobs:
  update_sheet:
    runs-on: ubuntu-latest
    steps:
      - name: 'get all added files in the PR'
        if: ${{ !env.ACT }}
        id: 'files'
        uses: mmagician/get-changed-files@master

      - name: Checkout
        uses: actions/checkout@master
        if: ${{ !env.ACT }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Local Testing Checkout
        uses: actions/checkout@master
        if: ${{ env.ACT }}

      # - name: 'local testing parse files'
      #   if: ${{ env.ACT }}
      #   id: grant_parser
      #   uses: mmagician/read-file-action@v2
      #   with:
      #     path: 'deliveries/.delivery_testing.md'

      - name: 'parse files'
        if: ${{ !env.ACT }}
        id: grant_parser
        uses: mmagician/read-file-action@v2
        with:
          path: "${{ github.workspace }}/${{ steps.files.outputs.added }}"

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d/%m/%Y')"

      - name: 'check author validity'
        id: 'validate_pr'
        uses: ./.github/actions/validate_pr
        with:
          targetRepoOwner: "w3f"
          targetRepo: "Open-Grants-Program"
          prLink: "${{ steps.grant_parser.outputs.contract_url }}"
          author: "${{ github.event.pull_request.author }}"

      - name: 'write the data to a gsheet'
        if: "${{ steps.validate_pr.outputs.isValid }}"
        id: 'update_worksheet'
        uses: jroehl/gsheet.action@v1.0.0 # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: ${{ secrets.SPREADSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { 
                "command": "appendData", 
                "args": 
                { 
                  "data": [[
                    "=INDEX(Legal!$A$7:$A$400,MATCH(INDIRECT(CONCATENATE(\"B\", TEXT(ROW(), \"#\"))),Legal!$D$7:$D$400,0))", 
                    "${{ steps.grant_parser.outputs.project_name }}", 
                    "${{ steps.grant_parser.outputs.milestone_number }}", 
                    "",
                    "Not Yet", 
                    "=INDEX(Legal!$W$7:$W$400,MATCH(INDIRECT(CONCATENATE(\"B\", TEXT(ROW(), \"#\"))),Legal!$D$7:$D$400,0))",
                    "", 
                    "${{ steps.date.outputs.date }}"
                  ]], 
                  "worksheetTitle": "Evaluation", 
                  "minCol": 1,
                  "valueInputOption": "USER_ENTERED"
                }
               }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
