name: comment_on_label

on:
  pull_request_target:
    types: [labeled]

jobs:
  last_milestone:
    if: github.event.label.name == 'last milestone'
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@1.0.2
        with:
          message: > 
            We noticed that this is the last milestone of your project, so what are the potential next steps?<br/>
            
            While you can always apply for a follow-up grant, the grants program might not be the best tool for your future growth. 
            Our main goal is to support research as well as early-stage technical projects. Below are a couple of other options in our ecosystem 
            that might be better suited as the next step: <br/> 

            Project with a Business Case/Token: [Substrate Builders Program](https://substrate.io/ecosystem/substrate-builders-program/) 
            or [VC Funding](https://parachains.info/investors) <br/> 

            Common Good Projects: [Treasury Funding](https://github.com/w3f/Grants-Program#treasury) <br/> 

            Let us know if you have any questions regarding the above. We are more than happy to help you with it. 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}